# Generated by Django 5.0.4 on 2024-05-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_something_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo_pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(null=True, upload_to='logos/')),
                ('Alt', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=20)),
                ('Url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
