# Generated by Django 5.0.4 on 2024-05-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_logo_pic_menu_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageTest',
            new_name='Carousel_Items',
        ),
    ]
