# Generated by Django 5.0.4 on 2024-05-06 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_imagetest_carousel_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel_Items',
        ),
    ]
