# Generated by Django 5.0.4 on 2024-05-06 06:30

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_delete_carousel_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel_Items',
            fields=[
                ('Carousel_id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[backend.models.validate_carousel_id])),
                ('Img', models.ImageField(null=True, upload_to='carousels/')),
                ('description', models.CharField(max_length=200, null=True)),
                ('alt', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
