# Generated by Django 5.0.4 on 2024-05-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_carousel_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FaviconDonors', models.ImageField(null=True, upload_to='Donors/')),
                ('Url', models.CharField(max_length=100, null=True)),
                ('Alt', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
