# Generated by Django 5.0.4 on 2024-05-07 02:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_donors'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, null=True)),
                ('ImgThumb', models.ImageField(null=True, upload_to='news/')),
                ('VideoUrl', models.CharField(blank=True, max_length=100, null=True)),
                ('UpdateAt', models.DateField(auto_now=True)),
                ('Content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
