# Generated by Django 5.0.4 on 2024-05-12 09:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_news_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_items',
            name='Content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
