# Generated by Django 5.0.4 on 2024-05-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_ona_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ona_items',
            name='Title',
            field=models.CharField(max_length=30),
        ),
    ]
