# Generated by Django 5.0.4 on 2024-05-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_story_items_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_items',
            name='Title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
