# Generated by Django 5.0.4 on 2024-05-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_story_items_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_items',
            name='SubTitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
