# Generated by Django 5.0.4 on 2024-05-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_story_items_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(null=True, upload_to='StaffCast/')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('Url', models.CharField(max_length=100, null=True)),
                ('Movie', models.CharField(max_length=20, null=True)),
                ('job', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
