# Generated by Django 5.0.4 on 2024-05-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_staff_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(null=True, upload_to='Trailers/')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('Url', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
