# Generated by Django 5.0.4 on 2024-05-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(null=True, upload_to='Musics/')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('Type', models.CharField(max_length=30, null=True)),
                ('Content', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
