# Generated by Django 5.0.4 on 2024-05-14 09:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='Content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
