# Generated by Django 5.0.4 on 2024-05-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_music_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
