# Generated by Django 5.0.4 on 2024-05-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_podcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
