# Generated by Django 5.0.4 on 2024-05-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_podcast_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Img', models.ImageField(null=True, upload_to='SNS/')),
                ('Url', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
