# Generated by Django 5.0.4 on 2024-05-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_sns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Img', models.ImageField(null=True, upload_to='Goods/')),
                ('SellDate', models.CharField(max_length=30, null=True)),
                ('Price', models.CharField(blank=True, max_length=30, null=True)),
                ('Category', models.CharField(max_length=20, null=True)),
                ('Description', models.CharField(max_length=200, null=True)),
                ('Url', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
