# Generated by Django 5.0.4 on 2024-05-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_category_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='Category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='Price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='SellDate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
